import React, { useEffect, useState, useCallback } from 'react';
import type { WeatherAlert, District } from '../types/weatherTypes';
import { fetchAlerts, fetchDistricts } from '../api/weatherApi';

const HAZARD_COLOR: Record<string, string> = {
  Flood: '#3b82f6',
  Landslide: '#f59e0b',
  StrongWind: '#a78bfa',
  'Strong Wind': '#a78bfa',
};
const HAZARD_ICON: Record<string, string> = {
  Flood: '🌊',
  Landslide: '⛰️',
  StrongWind: '💨',
  'Strong Wind': '💨',
};
const STATUS_STYLE: Record<string, { bg: string; color: string; label: string }> = {
  Published: { bg: 'rgba(16,185,129,0.12)', color: '#6ee7b7', label: '✅ Published' },
  PendingReview: { bg: 'rgba(245,158,11,0.12)', color: '#fcd34d', label: '⏳ Pending Review' },
  Rejected: { bg: 'rgba(239,68,68,0.12)', color: '#fca5a5', label: '❌ Rejected' },
};

export const PredictionHistoryPage: React.FC = () => {
  const [alerts, setAlerts] = useState<WeatherAlert[]>([]);
  const [total, setTotal] = useState(0);
  const [districts, setDistricts] = useState<District[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [filterStatus, setFilterStatus] = useState('');
  const [filterDistrict, setFilterDistrict] = useState('');
  const [filterHazard, setFilterHazard] = useState('');
  const [page, setPage] = useState(1);
  const pageSize = 20;

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await fetchAlerts({
        status: filterStatus || undefined,
        districtId: filterDistrict || undefined,
        hazardType: filterHazard || undefined,
        page,
        pageSize,
      });
      setAlerts(data.items);
      setTotal(data.total);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }, [filterStatus, filterDistrict, filterHazard, page]);

  useEffect(() => { load(); }, [load]);
  useEffect(() => { fetchDistricts().then(setDistricts); }, []);

  const totalPages = Math.ceil(total / pageSize);

  return (
    <div style={{ padding: '1.5rem 2rem' }}>
      <div style={{ marginBottom: '1.25rem' }}>
        <h2 style={{ margin: 0, color: '#f1f5f9', fontSize: '1.4rem', fontWeight: 700 }}>
          📜 Alert & Prediction History
        </h2>
        <p style={{ color: '#64748b', margin: '0.25rem 0 0', fontSize: '0.875rem' }}>
          Full audit trail of all alerts generated by the AI prediction agent
        </p>
      </div>

      {/* Filters */}
      <div style={{
        display: 'flex', gap: '0.75rem', flexWrap: 'wrap', marginBottom: '1rem',
        background: 'rgba(255,255,255,0.04)', borderRadius: 10, padding: '0.75rem 1rem',
        border: '1px solid rgba(255,255,255,0.06)'
      }}>
        <select
          value={filterStatus}
          onChange={e => { setFilterStatus(e.target.value); setPage(1); }}
          style={{ padding: '0.4rem 0.75rem', borderRadius: 6, background: '#1e293b', color: '#f1f5f9', border: '1px solid rgba(255,255,255,0.1)', fontSize: '0.82rem' }}
        >
          <option value="">All Statuses</option>
          <option value="Published">Published</option>
          <option value="PendingReview">Pending Review</option>
          <option value="Rejected">Rejected</option>
        </select>

        <select
          value={filterDistrict}
          onChange={e => { setFilterDistrict(e.target.value); setPage(1); }}
          style={{ padding: '0.4rem 0.75rem', borderRadius: 6, background: '#1e293b', color: '#f1f5f9', border: '1px solid rgba(255,255,255,0.1)', fontSize: '0.82rem' }}
        >
          <option value="">All Districts</option>
          {districts.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}
        </select>

        <select
          value={filterHazard}
          onChange={e => { setFilterHazard(e.target.value); setPage(1); }}
          style={{ padding: '0.4rem 0.75rem', borderRadius: 6, background: '#1e293b', color: '#f1f5f9', border: '1px solid rgba(255,255,255,0.1)', fontSize: '0.82rem' }}
        >
          <option value="">All Hazard Types</option>
          <option value="Flood">🌊 Flood</option>
          <option value="Landslide">⛰️ Landslide</option>
          <option value="StrongWind">💨 Strong Wind</option>
        </select>

        <button onClick={() => load()} style={{ padding: '0.4rem 0.75rem', borderRadius: 6, background: 'rgba(37,99,235,0.2)', color: '#93c5fd', border: '1px solid rgba(37,99,235,0.3)', cursor: 'pointer', fontSize: '0.82rem' }}>
          🔄 Refresh
        </button>

        <span style={{ marginLeft: 'auto', color: '#64748b', fontSize: '0.8rem', alignSelf: 'center' }}>
          {total} record{total !== 1 ? 's' : ''}
        </span>
      </div>

      {loading && <div style={{ textAlign: 'center', padding: '2rem', color: '#64748b' }}>Loading…</div>}
      {error && (
        <div style={{ padding: '1rem', background: 'rgba(239,68,68,0.1)', borderRadius: 8, border: '1px solid rgba(239,68,68,0.3)', color: '#fca5a5', marginBottom: '1rem' }}>
          ⚠️ {error}
        </div>
      )}

      {!loading && alerts.length === 0 && (
        <div style={{ textAlign: 'center', padding: '3rem', color: '#475569' }}>
          <div style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>📭</div>
          No records match the current filters.
        </div>
      )}

      {/* Table */}
      {alerts.length > 0 && (
        <div style={{ background: 'rgba(255,255,255,0.03)', borderRadius: 12, border: '1px solid rgba(255,255,255,0.07)', overflow: 'hidden' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.82rem' }}>
            <thead>
              <tr style={{ background: 'rgba(255,255,255,0.05)', borderBottom: '1px solid rgba(255,255,255,0.07)' }}>
                {['Hazard', 'District', 'Severity', 'Status', 'Created', 'Published'].map(h => (
                  <th key={h} style={{ padding: '0.75rem 1rem', textAlign: 'left', color: '#64748b', fontWeight: 600 }}>
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {alerts.map((a, i) => {
                const hColor = HAZARD_COLOR[a.hazardType] ?? '#94a3b8';
                const hIcon = HAZARD_ICON[a.hazardType] ?? '⚡';
                const sStyle = STATUS_STYLE[a.status] ?? { bg: 'rgba(148,163,184,0.1)', color: '#94a3b8', label: a.status };
                return (
                  <tr key={a.id} style={{ borderBottom: '1px solid rgba(255,255,255,0.04)', background: i % 2 === 0 ? 'transparent' : 'rgba(255,255,255,0.01)' }}>
                    <td style={{ padding: '0.7rem 1rem' }}>
                      <span style={{ color: hColor, fontWeight: 600 }}>{hIcon} {a.hazardType}</span>
                    </td>
                    <td style={{ padding: '0.7rem 1rem', color: '#cbd5e1' }}>
                      {a.districtName ?? '—'}
                    </td>
                    <td style={{ padding: '0.7rem 1rem' }}>
                      <span style={{
                        padding: '2px 8px', borderRadius: 4, fontSize: '0.72rem',
                        background: a.severity === 'High' ? 'rgba(239,68,68,0.12)' : 'rgba(245,158,11,0.12)',
                        color: a.severity === 'High' ? '#fca5a5' : '#fcd34d'
                      }}>
                        {a.severity}
                      </span>
                    </td>
                    <td style={{ padding: '0.7rem 1rem' }}>
                      <span style={{ padding: '2px 8px', borderRadius: 4, fontSize: '0.72rem', background: sStyle.bg, color: sStyle.color }}>
                        {sStyle.label}
                      </span>
                    </td>
                    <td style={{ padding: '0.7rem 1rem', color: '#64748b' }}>
                      {new Date(a.createdAt).toLocaleString('en-GB', { dateStyle: 'short', timeStyle: 'short' })}
                    </td>
                    <td style={{ padding: '0.7rem 1rem', color: '#64748b' }}>
                      {a.publishedAt
                        ? new Date(a.publishedAt).toLocaleString('en-GB', { dateStyle: 'short', timeStyle: 'short' })
                        : '—'}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* Pagination */}
      {totalPages > 1 && (
        <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'center', marginTop: '1.25rem' }}>
          <button onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1}
            style={{ padding: '0.4rem 0.75rem', borderRadius: 6, background: 'rgba(255,255,255,0.06)', color: '#94a3b8', border: '1px solid rgba(255,255,255,0.08)', cursor: 'pointer', opacity: page === 1 ? 0.4 : 1 }}>
            ‹ Prev
          </button>
          <span style={{ color: '#64748b', alignSelf: 'center', fontSize: '0.82rem' }}>
            Page {page} of {totalPages}
          </span>
          <button onClick={() => setPage(p => Math.min(totalPages, p + 1))} disabled={page === totalPages}
            style={{ padding: '0.4rem 0.75rem', borderRadius: 6, background: 'rgba(255,255,255,0.06)', color: '#94a3b8', border: '1px solid rgba(255,255,255,0.08)', cursor: 'pointer', opacity: page === totalPages ? 0.4 : 1 }}>
            Next ›
          </button>
        </div>
      )}
    </div>
  );
};
