// <auto-generated />
using System;
using Aegis.Recovery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aegis.Recovery.Migrations
{
    [DbContext(typeof(RecoveryDbContext))]
    [Migration("20260911091906_SyncRecoveryModel")]
    partial class SyncRecoveryModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("recovery")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aegis.Recovery.Models.AidRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AidType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FamilySize")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ShelterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VictimName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("District");

                    b.HasIndex("ShelterId");

                    b.HasIndex("Status");

                    b.ToTable("AidRequests", "recovery");
                });

            modelBuilder.Entity("Aegis.Recovery.Models.Compensation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("ClaimAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DamageCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NIC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NIC");

                    b.HasIndex("Status");

                    b.ToTable("Compensations", "recovery");
                });

            modelBuilder.Entity("Aegis.Recovery.Models.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllocationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("AmountOrQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DonationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DonorContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TargetShelterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetShelterId");

                    b.ToTable("Donations", "recovery");
                });

            modelBuilder.Entity("Aegis.Recovery.Models.InfrastructureDamage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DamageLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedRepairCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriorityScore")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("InfrastructureDamages", "recovery");
                });

            modelBuilder.Entity("Aegis.Recovery.Models.NGO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AssignedBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatingDistricts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sectors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("NGOs", "recovery");
                });

            modelBuilder.Entity("Aegis.Recovery.Models.RecoveryPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedTotalBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanSummaryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<int>("RevisionCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("Status");

                    b.ToTable("RecoveryPlans", "recovery");
                });

            modelBuilder.Entity("Aegis.Recovery.Models.RecoveryReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReportSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalAidRequestsFulfilled")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalBudgetSpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalCompensationDisbursed")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TotalSheltered")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("RecoveryReports", "recovery");
                });

            modelBuilder.Entity("Aegis.Recovery.Models.RecoveryTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedNGOId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RecoveryPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TargetCompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedNGOId");

                    b.HasIndex("RecoveryPlanId");

                    b.ToTable("RecoveryTasks", "recovery");
                });

            modelBuilder.Entity("Aegis.Recovery.Models.RecoveryWorkflowLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentStepsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApprovalDecision")
                        .HasColumnType("text");

                    b.Property<string>("ApprovalNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovalTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Errors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExecutionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExecutionSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectiveJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecoveryPlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("ToolCallsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalDurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ValidationResultsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionStatus");

                    b.HasIndex("RecoveryPlanId")
                        .IsUnique();

                    b.ToTable("RecoveryWorkflowLogs", "recovery");
                });

            modelBuilder.Entity("Aegis.Recovery.Models.Shelter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentOccupancy")
                        .HasColumnType("integer");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Facilities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("District");

                    b.HasIndex("Status");

                    b.ToTable("Shelters", "recovery");
                });

            modelBuilder.Entity("Aegis.Recovery.Models.AidRequest", b =>
                {
                    b.HasOne("Aegis.Recovery.Models.Shelter", "Shelter")
                        .WithMany("AidRequests")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("Aegis.Recovery.Models.Donation", b =>
                {
                    b.HasOne("Aegis.Recovery.Models.Shelter", "TargetShelter")
                        .WithMany("Donations")
                        .HasForeignKey("TargetShelterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TargetShelter");
                });

            modelBuilder.Entity("Aegis.Recovery.Models.RecoveryTask", b =>
                {
                    b.HasOne("Aegis.Recovery.Models.NGO", "AssignedNGO")
                        .WithMany()
                        .HasForeignKey("AssignedNGOId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aegis.Recovery.Models.RecoveryPlan", "RecoveryPlan")
                        .WithMany("Tasks")
                        .HasForeignKey("RecoveryPlanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AssignedNGO");

                    b.Navigation("RecoveryPlan");
                });

            modelBuilder.Entity("Aegis.Recovery.Models.RecoveryWorkflowLog", b =>
                {
                    b.HasOne("Aegis.Recovery.Models.RecoveryPlan", "RecoveryPlan")
                        .WithOne("WorkflowLog")
                        .HasForeignKey("Aegis.Recovery.Models.RecoveryWorkflowLog", "RecoveryPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecoveryPlan");
                });

            modelBuilder.Entity("Aegis.Recovery.Models.RecoveryPlan", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("WorkflowLog");
                });

            modelBuilder.Entity("Aegis.Recovery.Models.Shelter", b =>
                {
                    b.Navigation("AidRequests");

                    b.Navigation("Donations");
                });
#pragma warning restore 612, 618
        }
    }
}
