// <auto-generated />
using System;
using Aegis.Weather.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aegis.Weather.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20260810061803_AddLandslideAndWindHazards")]
    partial class AddLandslideAndWindHazards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("weather")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aegis.Weather.Models.AgentExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TriggeredByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AgentExecutionLogs", "weather");
                });

            modelBuilder.Entity("Aegis.Weather.Models.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLandslideProne")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Districts", "weather");
                });

            modelBuilder.Entity("Aegis.Weather.Models.ForecastHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("ActualDisasterOccurred")
                        .HasColumnType("boolean");

                    b.Property<double?>("ActualValue")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PredictionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PredictionId");

                    b.ToTable("ForecastHistory", "weather");
                });

            modelBuilder.Entity("Aegis.Weather.Models.HistoricalWeather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AvgRainfallMm")
                        .HasColumnType("double precision");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<double>("FloodThresholdMm")
                        .HasColumnType("double precision");

                    b.Property<double>("HighWindThresholdKmh")
                        .HasColumnType("double precision");

                    b.Property<double?>("LandslideThresholdMm")
                        .HasColumnType("double precision");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId", "Month")
                        .IsUnique();

                    b.ToTable("HistoricalWeather", "weather");
                });

            modelBuilder.Entity("Aegis.Weather.Models.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<double>("ConfidencePct")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<double>("ForecastValue")
                        .HasColumnType("double precision");

                    b.Property<string>("HazardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("HistoricalThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("RiskProbabilityPct")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId", "HazardType", "CreatedAt");

                    b.ToTable("Predictions", "weather");
                });

            modelBuilder.Entity("Aegis.Weather.Models.WeatherAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<string>("HazardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PredictionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PredictionId")
                        .IsUnique();

                    b.HasIndex("DistrictId", "HazardType", "Status");

                    b.ToTable("WeatherAlerts", "weather");
                });

            modelBuilder.Entity("Aegis.Weather.Models.WeatherObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("RainfallMm")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeedKmh")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("WeatherObservations", "weather");
                });

            modelBuilder.Entity("Aegis.Weather.Models.WeatherStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("WeatherStations", "weather");
                });

            modelBuilder.Entity("Aegis.Weather.Models.ForecastHistory", b =>
                {
                    b.HasOne("Aegis.Weather.Models.Prediction", "Prediction")
                        .WithMany()
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("Aegis.Weather.Models.HistoricalWeather", b =>
                {
                    b.HasOne("Aegis.Weather.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Aegis.Weather.Models.Prediction", b =>
                {
                    b.HasOne("Aegis.Weather.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Aegis.Weather.Models.WeatherAlert", b =>
                {
                    b.HasOne("Aegis.Weather.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aegis.Weather.Models.Prediction", "Prediction")
                        .WithOne("Alert")
                        .HasForeignKey("Aegis.Weather.Models.WeatherAlert", "PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("Aegis.Weather.Models.WeatherObservation", b =>
                {
                    b.HasOne("Aegis.Weather.Models.WeatherStation", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Aegis.Weather.Models.WeatherStation", b =>
                {
                    b.HasOne("Aegis.Weather.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Aegis.Weather.Models.Prediction", b =>
                {
                    b.Navigation("Alert");
                });
#pragma warning restore 612, 618
        }
    }
}
